apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

images:
  - name: creativeanchor/creative-anchor
    newName: creativeanchoracr.azurecr.io/creativeanchor/creative-anchor
    newTag: latest
