apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv
    kind: ClusterSecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: database-url
      remoteRef:
        key: database-url
    - secretKey: db-user
      remoteRef:
        key: db-user
    - secretKey: db-password
      remoteRef:
        key: db-password
    - secretKey: app-secret-key
      remoteRef:
        key: app-secret-key
