apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv
    kind: ClusterSecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: supabase-url
      remoteRef:
        key: supabase-url
    - secretKey: supabase-key
      remoteRef:
        key: supabase-key
    - secretKey: gemini-api-key
      remoteRef:
        key: gemini-api-key
    - secretKey: app-secret-key
      remoteRef:
        key: app-secret-key
