apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-kv
spec:
  provider:
    azurekv:
      tenantId: REPLACE_WITH_TENANT_ID
      vaultUrl: https://REPLACE_WITH_KV_NAME.vault.azure.net/
      authType: WorkloadIdentity
      serviceAccountRef:
        name: external-secrets-sa
        namespace: external-secrets
