apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monolith-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/TUES-2026-PBL-11-klas/Colonel-Sanders-CreativeAnchor"
    targetRevision: main
    path: gitops/services/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - PruneLast=true
