apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: supabase-secrets
  namespace: supabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv
    kind: ClusterSecretStore
  target:
    name: supabase-secrets
    creationPolicy: Owner
  data:
    - secretKey: db-name
      remoteRef:
        key: supabase-db-name
    - secretKey: db-user
      remoteRef:
        key: supabase-db-user
    - secretKey: db-password
      remoteRef:
        key: supabase-db-password
    - secretKey: db-url
      remoteRef:
        key: supabase-db-url
    - secretKey: jwt-secret
      remoteRef:
        key: supabase-jwt-secret
    - secretKey: anon-key
      remoteRef:
        key: supabase-anon-key
    - secretKey: service-role-key
      remoteRef:
        key: supabase-service-role-key
