apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: supabase-kong
  namespace: supabase
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: supabase-kong
                port:
                  number: 80
