apiVersion: v1
kind: Service
metadata:
  name: supabase-postgres
  namespace: supabase
  labels:
    app: supabase-postgres
spec:
  clusterIP: None
  selector:
    app: supabase-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
