apiVersion: v1
kind: Service
metadata:
  name: supabase-rest
  namespace: supabase
  labels:
    app: supabase-rest
spec:
  selector:
    app: supabase-rest
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
