apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-rest
  namespace: supabase
  labels:
    app: supabase-rest
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: supabase-rest
  template:
    metadata:
      labels:
        app: supabase-rest
    spec:
      containers:
        - name: rest
          image: postgrest/postgrest:v12.2.0
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: db-password
            - name: PGRST_DB_URI
              value: postgresql://authenticator:$(DB_PASSWORD)@supabase-postgres.supabase.svc.cluster.local:5432/postgres
            - name: PGRST_DB_SCHEMA
              value: public,storage,graphql_public
            - name: PGRST_DB_ANON_ROLE
              value: anon
            - name: PGRST_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: jwt-secret
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          ports:
            - containerPort: 3000
