apiVersion: v1
kind: Service
metadata:
  name: supabase-storage
  namespace: supabase
  labels:
    app: supabase-storage
spec:
  selector:
    app: supabase-storage
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
