serviceAccount:
  create: true
  name: external-secrets-sa
  annotations:
    azure.workload.identity/client-id: ${eso_client_id}

installCRDs: true

env:
  - name: AZURE_AUTH_METHOD
    value: "WorkloadIdentity"
